config/routes.rb
Rails.application.routes.draw do
  resources :contact_groups
  resources :groups
  resources :emails
  resources :phones
  resources :notes
  resources :contacts
  resources :ringtones
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact_group.rb
class ContactGroup < ApplicationRecord

	belongs_to 	:contact
	belongs_to 	:group
end

app/controllers/contact_groups_controller.rb
class ContactGroupsController < ApplicationController
  before_action :set_contact_group, only: [:show, :edit, :update, :destroy]

  # GET /contact_groups
  # GET /contact_groups.json
  def index
    @contact_groups = ContactGroup.all
  end

  # GET /contact_groups/1
  # GET /contact_groups/1.json
  def show
  end

  # GET /contact_groups/new
  def new
    @contact_group = ContactGroup.new
  end

  # GET /contact_groups/1/edit
  def edit
  end

  # POST /contact_groups
  # POST /contact_groups.json
  def create
    @contact_group = ContactGroup.new(contact_group_params)

    respond_to do |format|
      if @contact_group.save
        format.html { redirect_to @contact_group, notice: 'Contact group was successfully created.' }
        format.json { render :show, status: :created, location: @contact_group }
      else
        format.html { render :new }
        format.json { render json: @contact_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_groups/1
  # PATCH/PUT /contact_groups/1.json
  def update
    respond_to do |format|
      if @contact_group.update(contact_group_params)
        format.html { redirect_to @contact_group, notice: 'Contact group was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_group }
      else
        format.html { render :edit }
        format.json { render json: @contact_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_groups/1
  # DELETE /contact_groups/1.json
  def destroy
    @contact_group.destroy
    respond_to do |format|
      format.html { redirect_to contact_groups_url, notice: 'Contact group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_group
      @contact_group = ContactGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_group_params
      params.require(:contact_group).permit(:contact_id, :group_id)
    end
end

app/helpers/contact_groups_helper.rb
module ContactGroupsHelper
end

app/views/contact_groups/_form.html.erb
<%= form_for(contact_group) do |f| %>
  <% if contact_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact_group.errors.count, "error") %> prohibited this contact_group from being saved:</h2>

      <ul>
      <% contact_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contact_id %>
    <%= f.number_field :contact_id %>
  </div>

  <div class="field">
    <%= f.label :group_id %>
    <%= f.number_field :group_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_groups/edit.html.erb
<h1>Editing Contact Group</h1>

<%= render 'form', contact_group: @contact_group %>

<%= link_to 'Show', @contact_group %> |
<%= link_to 'Back', contact_groups_path %>

app/views/contact_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact Groups</h1>

<table>
  <thead>
    <tr>
      <th>Contact</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_groups.each do |contact_group| %>
      <tr>
        <td><%= contact_group.contact_id %></td>
        <td><%= contact_group.group_id %></td>
        <td><%= link_to 'Show', contact_group %></td>
        <td><%= link_to 'Edit', edit_contact_group_path(contact_group) %></td>
        <td><%= link_to 'Destroy', contact_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Group', new_contact_group_path %>

app/views/contact_groups/new.html.erb
<h1>New Contact Group</h1>

<%= render 'form', contact_group: @contact_group %>

<%= link_to 'Back', contact_groups_path %>

app/views/contact_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contact:</strong>
  <%= @contact_group.contact_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @contact_group.group_id %>
</p>

<%= link_to 'Edit', edit_contact_group_path(@contact_group) %> |
<%= link_to 'Back', contact_groups_path %>