config/routes.rb
Rails.application.routes.draw do
  resources :contact_groups
  resources :groups
  resources :emails
  resources :phones
  resources :notes
  resources :contacts
  resources :ringtones
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ringtone.rb
class Ringtone < ApplicationRecord
	
	has_many 	:contacts

	belongs_to 	:ringtone
end

app/controllers/ringtones_controller.rb
class RingtonesController < ApplicationController
  before_action :set_ringtone, only: [:show, :edit, :update, :destroy]

  # GET /ringtones
  # GET /ringtones.json
  def index
    @ringtones = Ringtone.all
  end

  # GET /ringtones/1
  # GET /ringtones/1.json
  def show
  end

  # GET /ringtones/new
  def new
    @ringtone = Ringtone.new
  end

  # GET /ringtones/1/edit
  def edit
  end

  # POST /ringtones
  # POST /ringtones.json
  def create
    @ringtone = Ringtone.new(ringtone_params)

    respond_to do |format|
      if @ringtone.save
        format.html { redirect_to @ringtone, notice: 'Ringtone was successfully created.' }
        format.json { render :show, status: :created, location: @ringtone }
      else
        format.html { render :new }
        format.json { render json: @ringtone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ringtones/1
  # PATCH/PUT /ringtones/1.json
  def update
    respond_to do |format|
      if @ringtone.update(ringtone_params)
        format.html { redirect_to @ringtone, notice: 'Ringtone was successfully updated.' }
        format.json { render :show, status: :ok, location: @ringtone }
      else
        format.html { render :edit }
        format.json { render json: @ringtone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ringtones/1
  # DELETE /ringtones/1.json
  def destroy
    @ringtone.destroy
    respond_to do |format|
      format.html { redirect_to ringtones_url, notice: 'Ringtone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ringtone
      @ringtone = Ringtone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ringtone_params
      params.require(:ringtone).permit(:name, :file)
    end
end

app/helpers/ringtones_helper.rb
module RingtonesHelper
end

app/views/ringtones/_form.html.erb
<%= form_for(ringtone) do |f| %>
  <% if ringtone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ringtone.errors.count, "error") %> prohibited this ringtone from being saved:</h2>

      <ul>
      <% ringtone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ringtones/edit.html.erb
<h1>Editing Ringtone</h1>

<%= render 'form', ringtone: @ringtone %>

<%= link_to 'Show', @ringtone %> |
<%= link_to 'Back', ringtones_path %>

app/views/ringtones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ringtones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ringtones.each do |ringtone| %>
      <tr>
        <td><%= ringtone.name %></td>
        <td><%= ringtone.file %></td>
        <td><%= link_to 'Show', ringtone %></td>
        <td><%= link_to 'Edit', edit_ringtone_path(ringtone) %></td>
        <td><%= link_to 'Destroy', ringtone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ringtone', new_ringtone_path %>

app/views/ringtones/new.html.erb
<h1>New Ringtone</h1>

<%= render 'form', ringtone: @ringtone %>

<%= link_to 'Back', ringtones_path %>

app/views/ringtones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ringtone.name %>
</p>

<p>
  <strong>File:</strong>
  <%= @ringtone.file %>
</p>

<%= link_to 'Edit', edit_ringtone_path(@ringtone) %> |
<%= link_to 'Back', ringtones_path %>